font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        12.0

symbol_map U+e000-U+f8ff Symbols Nerd Font Mono

window_padding_width 20

background_opacity 1.0

background_blur 8

hide_window_decorations yes

confirm_os_window_close 0

cursor_shape           beam
cursor_beam_thickness  1.5
cursor_blink_interval  0.5

cursor_trail                 10
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 2

scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

copy_on_select yes
strip_trailing_spaces smart

detect_urls yes
url_style curly
open_url_with default

mouse_hide_wait 3.0

map ctrl+shift+n new_window
map ctrl+t new_tab

map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+shift+k clear_terminal scrollback active

tab_bar_style powerline
tab_bar_align left
tab_powerline_style slanted

active_tab_font_style bold
inactive_tab_font_style normal

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell yes

sync_to_monitor yes

repaint_delay 10
input_delay 3

shell_integration enabled

include dank-tabs.conf
include dank-theme.conf