general {
    lock_cmd = /home/pradun/.config/hypr/scripts/qs_dialog.sh lockscreen open
    before_sleep_cmd = /home/pradun/.config/hypr/scripts/qs_dialog.sh lockscreen open
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Dim laptop screen
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 2. Lock screen with Quickshell
listener {
    timeout = 600
    on-timeout = /home/pradun/.config/hypr/scripts/qs_dialog.sh lockscreen open
}

# 3. Turn off monitor outputs
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend laptop
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
EOF && killall hypridle; hypridle &
