hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP QT_QPA_PLATFORMTHEME")
    
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("/usr/libexec/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("awww-daemon &")
    hl.exec_cmd("waypaper --restore &")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3")
    hl.exec_cmd("gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'")
    hl.exec_cmd([[sh -c 'echo "$HOME/.config/hypr/dms/colors.conf" | entr -n "$HOME/.config/hypr/scripts/apply_preset.sh" 0 &' ]])
end)