-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "400x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@143.997", position = "1920x693", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", mode = "1920x1080@144.001", position = "0x693", scale = 1, vrr = 0 })
